global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "rules/*.yml"

scrape_configs:
  - job_name: 'flashcard-app'
    static_configs:
      - targets: ['flashcard-app:9000']
    scrape_interval: 30s
    metrics_path: /metrics
    
  - job_name: 'flashcard-app-health'
    static_configs:
      - targets: ['flashcard-app:8000']
    scrape_interval: 30s
    metrics_path: /health
    
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093